# Generated by Django 4.2.7 on 2023-12-07 05:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authen', '0002_kitchenlike'),
    ]

    operations = [
        migrations.AddField(
            model_name='kitchenuser',
            name='delivery',
            field=models.ManyToManyField(blank=True, null=True, related_name='delivery', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='kitchenuser',
            name='user_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL),
        ),
    ]
