# Generated by Django 4.2.7 on 2023-12-04 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authen', '0003_customuser_active_profile_customuser_kitchen_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='active_profile',
            field=models.BooleanField(default=False),
        ),
    ]
