# Generated by Django 4.2.7 on 2023-12-05 08:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authen', '0004_alter_customuser_active_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='kitchen_name',
        ),
        migrations.CreateModel(
            name='KitchenUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=250, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='logo_kitchen')),
                ('is_active', models.BooleanField(default=False)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('user_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
