# Generated by Django 4.2.7 on 2023-12-07 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authen', '0004_customuser_active_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='user_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
