# Generated by Django 4.2.7 on 2023-12-05 08:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authen', '0005_remove_customuser_kitchen_name_kitchenuser'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='active_profile',
        ),
    ]
