# Generated by Django 4.2.7 on 2023-12-13 06:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authen', '0005_customuser_user_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='kitchenlike',
            old_name='id_kitchen',
            new_name='kitchen',
        ),
        migrations.RenameField(
            model_name='kitchenlike',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='kitchenuser',
            old_name='user_id',
            new_name='user',
        ),
    ]
