# Generated by Django 4.2.7 on 2023-12-05 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authen', '0006_remove_customuser_active_profile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='kitchenuser',
            old_name='date',
            new_name='create_at',
        ),
        migrations.AddField(
            model_name='kitchenuser',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
