# Generated by Django 4.2.7 on 2023-12-24 19:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authen', '0006_customuser_latitude_customuser_longitude'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Role',
        ),
    ]
