# Generated by Django 4.2.7 on 2023-12-18 09:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authen', '0006_rename_id_kitchen_kitchenlike_kitchen_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='kitchenuser',
            old_name='delivery',
            new_name='deliveryman_user',
        ),
    ]
