# Generated by Django 4.2.7 on 2023-12-18 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authen', '0007_rename_delivery_kitchenuser_deliveryman_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kitchenuser',
            name='working_time',
        ),
        migrations.AddField(
            model_name='kitchenuser',
            name='close_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='kitchenuser',
            name='open_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
