# Generated by Django 4.2.7 on 2023-12-05 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authen', '0007_rename_date_kitchenuser_create_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='kitchenuser',
            name='latitude',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='kitchenuser',
            name='longitude',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='kitchenuser',
            name='working_time',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
