# Generated by Django 4.2.7 on 2023-11-28 12:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FoodCategories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categor_name', models.CharField(blank=True, max_length=100, null=True)),
                ('categor_img', models.ImageField(blank=True, null=True, upload_to='categor_img')),
            ],
        ),
        migrations.CreateModel(
            name='Foods',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=250, null=True)),
                ('content', models.TextField(blank=True, null=True)),
                ('ingredients', models.JSONField(blank=True, null=True)),
                ('recipe', models.JSONField(blank=True, null=True)),
                ('like', models.IntegerField(blank=True, default=0, null=True)),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('categories_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='recipe.foodcategories')),
                ('user_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='FoodFiles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('food_files', models.FileField(blank=True, null=True, upload_to='food_files/')),
                ('food_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='recipe.foods')),
            ],
        ),
    ]
