# Generated by Django 4.2.7 on 2023-12-04 11:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0002_alter_foodfiles_food_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foodfiles',
            name='food_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='food_files', to='recipe.foods'),
        ),
        migrations.CreateModel(
            name='FoodLike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('line', models.IntegerField(blank=True, default=0, null=True)),
                ('food_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='foods', to='recipe.foods')),
            ],
        ),
    ]
