# Generated by Django 4.2.7 on 2023-12-21 09:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('kitchen', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foods', models.JSONField(blank=True, null=True)),
                ('total_price', models.IntegerField(blank=True, null=True)),
                ('is_delivery', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=False)),
                ('address', models.CharField(max_length=250)),
                ('latitude', models.CharField(max_length=250, null=True)),
                ('longitude', models.CharField(blank=True, max_length=250)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('delivery', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='delivery_id', to=settings.AUTH_USER_MODEL)),
                ('kitchen', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='kitchen', to='kitchen.restaurants')),
                ('klient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='klient_id', to=settings.AUTH_USER_MODEL)),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order.orderstatus')),
            ],
        ),
    ]
