# Generated by Django 4.2.7 on 2023-12-24 14:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='orders',
            table='order_table',
        ),
        migrations.AlterModelTable(
            name='orderstatus',
            table='order_status',
        ),
    ]
