# Generated by Django 4.2.7 on 2023-12-28 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kitchen', '0003_rename_deliveryman_user_restaurants_employes'),
        ('order', '0002_alter_orders_table_alter_orderstatus_table'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orders',
            name='kitchen',
        ),
        migrations.AddField(
            model_name='orders',
            name='kitchen',
            field=models.ManyToManyField(blank=True, null=True, related_name='kitchen', to='kitchen.restaurants'),
        ),
    ]
