# Generated by Django 4.2.7 on 2023-12-24 14:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kitchen', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='restaurants',
            table='restaurant_table',
        ),
    ]
