# Generated by Django 4.2.7 on 2023-12-13 06:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kitchen', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='kitchenfoods',
            old_name='kitchen_id',
            new_name='kitchen',
        ),
        migrations.RenameField(
            model_name='kitchenfoods',
            old_name='user_id',
            new_name='user',
        ),
    ]
