# Generated by Django 4.2.7 on 2023-12-05 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kitchen', '0002_kitchenfoods_kitchen_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='kitchenfoods',
            old_name='date',
            new_name='create_at',
        ),
        migrations.AddField(
            model_name='kitchenfoods',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
