# Generated by Django 4.2.7 on 2023-12-27 16:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kitchen', '0002_alter_restaurants_table'),
    ]

    operations = [
        migrations.RenameField(
            model_name='restaurants',
            old_name='deliveryman_user',
            new_name='employes',
        ),
    ]
