# Generated by Django 4.2.7 on 2023-12-06 04:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authen', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FoodsCategories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('kitchen_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authen.kitchenuser')),
            ],
        ),
        migrations.CreateModel(
            name='Foods',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('food_img', models.ImageField(upload_to='foods')),
                ('content', models.TextField()),
                ('price', models.CharField(max_length=100)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('categories_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='foods.foodscategories')),
                ('kitchen_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authen.kitchenuser')),
            ],
        ),
    ]
