# Generated by Django 4.2.7 on 2023-12-24 14:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foods', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='foods',
            table='food_table',
        ),
        migrations.AlterModelTable(
            name='foodscategories',
            table='food_category_table',
        ),
    ]
