# Generated by Django 4.2.7 on 2023-12-13 06:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foods', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='foods',
            old_name='categories_id',
            new_name='categories',
        ),
        migrations.RenameField(
            model_name='foods',
            old_name='content',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='foods',
            old_name='kitchen_id',
            new_name='kitchen',
        ),
        migrations.RenameField(
            model_name='foodscategories',
            old_name='kitchen_id',
            new_name='kitchen',
        ),
    ]
