# Generated by Django 4.2.7 on 2023-12-19 11:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foods', '0002_rename_categories_id_foods_categories_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='foodscategories',
            name='kitchen',
        ),
    ]
