# Generated by Django 4.2.7 on 2023-12-21 05:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('foods', '0003_remove_foodscategories_kitchen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foods',
            name='categories',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='foods', to='foods.foodscategories'),
        ),
    ]
