# Generated by Django 4.2.7 on 2023-12-25 14:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kitchen', '0002_alter_restaurants_table'),
        ('foods', '0005_alter_favorite_food'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foods',
            name='kitchen',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='food', to='kitchen.restaurants'),
        ),
    ]
