# Generated by Django 4.2.7 on 2023-12-07 09:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('delivery', '0003_alter_delivery_delivery'),
    ]

    operations = [
        migrations.AlterField(
            model_name='delivery',
            name='foods',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='delivery',
            name='klient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='klient_id', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='delivery',
            name='latitude',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='delivery',
            name='longitude',
            field=models.CharField(blank=True, max_length=250),
        ),
    ]
