# Generated by Django 4.2.7 on 2023-12-07 11:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0005_grade_ordercoment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordercoment',
            name='delivery',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order', to='delivery.delivery'),
        ),
    ]
