# Generated by Django 4.2.7 on 2023-12-12 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0006_alter_ordercoment_delivery'),
    ]

    operations = [
        migrations.AddField(
            model_name='delivery',
            name='total_price',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
