# Generated by Django 4.2.7 on 2023-12-12 13:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0009_alter_ordercoment_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordercoment',
            name='delivery',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='order', to='delivery.delivery'),
        ),
    ]
