on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy back-ui
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          password: ${{ secrets.SSH_PASSWORD }}
          key: ${{ secrets.SSH_KEY }}

          script: |
            cd /var/www/food-delivery/ui-back
            git pull
            npm i --force
            rm -r dist
            npm run build
            sudo nginx -t
            sudo systemctl restart nginx
            echo "Deployed Success"
      
      - name: Deploy ui
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          password: ${{ secrets.SSH_PASSWORD }}
          key: ${{ secrets.SSH_KEY }}

          script: |
            cd /var/www/food-delivery/ui
            git pull
            npm i --force
            rm -r dist
            npm run build
            sudo nginx -t
            sudo systemctl restart nginx
            echo "Deployed Success"

      - name: Deploy Server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          password: ${{ secrets.SSH_PASSWORD }}

          script: |
            cd /var/www/food-delivery/back-end
            git pull
            source env/bin/activate
            python3 -m pip install -r requirements.txt
            python3 manage.py makemigrations authen foods order kitchen
            python3 manage.py migrate
            deactivate
            sudo systemctl start food.socket
            sudo systemctl enable food.socket
            sudo systemctl daemon-reload
            sudo systemctl restart food
            echo "Deployed at BackEnd"
      - name: deploy auth Server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          password: ${{ secrets.SSH_PASSWORD }}

          script: |
            cd /var/www/food-delivery/authentication
            git pull
            source env/bin/activate
            python3 -m pip install -r requirements.txt
            python3 manage.py makemigrations authen foods order kitchen
            python3 manage.py migrate
            deactivate
            sudo systemctl start auth-delivery.socket
            sudo systemctl enable auth-delivery.socket
            sudo systemctl daemon-reload
            sudo systemctl restart food
            echo "Deployed at auth"